@echo off
AMIDEWINx64.exe /IVN %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /IV  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /ID  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /SM  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /SP  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /SV  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /SS  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /SU  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /SK  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /SF  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /BM  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /BP  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /BV  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /BS  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /BT  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /BLC %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /CM  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /CT  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /CA  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /CS  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /CV  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /CO  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /CPC %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /CSK %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /CH  %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /PSN %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /PAT %random%--%random%-%random%-Spoofer
AMIDEWINx64.exe /PPN %random%--%random%-%random%-Spoofer